# Generated by Django 2.2 on 2019-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_auto_20190408_0023")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook_id",
            field=models.CharField(blank=True, max_length=200, unique=True),
        )
    ]
