# Generated by Django 2.2 on 2019-04-10 03:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("casts", "0004_auto_20190408_0023"),
        ("users", "0005_auto_20190408_0023"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("venue", models.CharField(max_length=256)),
                ("start", models.DateTimeField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="casts.Cast",
                    ),
                ),
            ],
            options={"ordering": ["start"]},
        ),
        migrations.CreateModel(
            name="Casting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (1, "Dr. Frank-N-Furter"),
                            (2, "Janet Weiss"),
                            (3, "Brad Majors"),
                            (4, "Riff Raff"),
                            (5, "Magenta"),
                            (6, "Columbia"),
                            (7, "Dr. Everett V. Scott"),
                            (8, "Rocky Horror"),
                            (9, "Eddie"),
                            (10, "The Criminologist"),
                            (11, "Transylvanian"),
                            (20, "Emcee"),
                            (21, "Trixie"),
                            (30, "Tech"),
                            (31, "Lights"),
                            (32, "Photographer"),
                        ]
                    ),
                ),
                ("writein", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="castings",
                        to="events.Event",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="castings",
                        to="users.Profile",
                    ),
                ),
            ],
            options={"ordering": ["role"]},
        ),
    ]
