# Generated by Django 2.1.7 on 2019-04-07 17:07

import casts.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [("casts", "0002_auto_20190402_0149")]

    operations = [
        migrations.AlterField(
            model_name="cast", name="description", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="cast", name="email", field=models.EmailField(max_length=128)
        ),
        migrations.AlterField(
            model_name="cast", name="external_url", field=models.URLField(blank=True)
        ),
        migrations.AlterField(
            model_name="cast", name="facebook_url", field=models.URLField(blank=True)
        ),
        migrations.AlterField(
            model_name="cast",
            name="instagram_user",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="cast",
            name="logo",
            field=sorl.thumbnail.fields.ImageField(
                blank=True, upload_to=casts.models.cast_logo
            ),
        ),
        migrations.AlterField(
            model_name="cast",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="cast",
            name="twitter_user",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="pagesection", name="text", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
