# Generated by Django 2.1.7 on 2019-04-08 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("casts", "0003_auto_20190407_1707")]

    operations = [
        migrations.RenameField(
            model_name="cast", old_name="created_date", new_name="created"
        ),
        migrations.RenameField(
            model_name="cast", old_name="modified_date", new_name="modified"
        ),
        migrations.RenameField(
            model_name="castphoto", old_name="created_date", new_name="created"
        ),
        migrations.RenameField(
            model_name="pagesection", old_name="created_date", new_name="created"
        ),
    ]
